
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 155407238003.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -f Dockerfile.train -t chest-ct-training .
      - docker tag chest-ct-training:latest 155407238003.dkr.ecr.us-east-1.amazonaws.com/chest-ct-training:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 155407238003.dkr.ecr.us-east-1.amazonaws.com/chest-ct-training:latest
      - echo Build completed on `date`