FROM tensorflow/tensorflow:2.15.0

RUN apt-get update && apt-get install -y \
    awscli \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install numpy==1.23.5 \
                boto3==1.34.0 \
                mlflow==2.8.0 \
                requests==2.31.0

WORKDIR /app
COPY scripts/ /app/scripts/

ENTRYPOINT ["python", "/app/scripts/retrain.py"]